name: CI-CD Pipeline  # isim vermek icin kullaniriz

on:
  workflow_dispatch: # manuel olarak kodumuzu calistirmamizi saglar
  schedule: # kodumuzu hangi zaman araliklarinda calistirmak istiyoruz.
    # - cron: '0 8 * * *' # her gun sabah 8 de calissin.
  push: # main branche her push yaptigimizda kod calisir
    branches:
      - main
  pull_request:

jobs:
  build: # ilk job
    runs-on: ubuntu-latest
    name: Build job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Echo user login
        run: echo "Hello, ${{ github.actor }}"

test: # ikinci job âœ… ARTIK jobs ALTINDA
    runs-on: ubuntu-latest
    name: Cypress Test Job
    container:
      image: cypress/base:latest # cypress docker cont. kurmus oluyoruz.
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js # node.js kuruyoruz
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies # dependencies kuruyoruz
        run: npm install

      - name: Run Cypress tests # testimizi calistiriyoruz.
        run: npx cypress run

      - name: UploadCypress videos # otomasyonumuzda videolari kaydediyoruz
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-videos
          path: cypress/videos/**/*.mp4
          retention-days: 1

      - name: UploadCypress screenshots # otomasyonumuzda ekran goruntulerini kaydediyoruz
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: cypress-screenshots
          path: cypress/screenshots/**/*.png
          retention-days: 1
